### ISSUE TITLE
Using an existing structured format

### ISSUE THREAD

**Issue by ColinMaudry** [flusio/gdpr-txt#1]
Since the purpose here is to publish data that can be both read by human (visitors who opened example.com/GDPR.txt), I suggest we promote a format that eases the parsing by a machine. Or would it be just for humans?

Since you already suggest a little of formalism, I think we could go as far as using [YAML](https://en.wikipedia.org/wiki/YAML#Basic_components). It's a very simple data structure and it would easily enable automated parsing.

Other flavours of JSON might work too.

**Comment by ColinMaudry** [comment]
It could look like that:

```yaml
---
# The list of purpose blocks
purposes:
- purpose: Connect users to their accounts
  lawfulness: legitimate interest
- purpose: Collect phone numbers
  lawfulness: legal

# The list of (collected) data blocks
collected:
- data: username
  required: true
  visibility: private
  description: The username is used to identify users during the login process.
  mitigation: Username does not have to be a real or known identity.
- data: password
  required: true
  visibility: private
  description: The password is used to check identity of users during the login process.

# Mutli line is possible like that
  mitigation: |
    Only hashes of the passwords are stored in database (but they transit
    over the network).

    It uses bcrypt to create the hashes.
```
